# SPDX-FileCopyrightText: The openTCS Authors
# SPDX-License-Identifier: MIT

[versions]
opentcs-baseline = "6.6.0"
# Other dependency versions
checkstyle = "10.21.4"
commons-io = "2.13.0"
eclipse-paho = "1.2.5"
everit-json-schema = "1.14.6"
google-code-findbugs = "3.0.2"
jackson = "2.20.0"
slf4j = "2.0.17"
# Test dependency versions
approvaltests = "25.7.0"
assertj = "3.27.6"
hamcrest = "3.0"
junit = "6.0.0"
junit-platform-launcher = "6.0.0"
mockito = "5.20.0"
# Plugin versions
jacocolog = "3.1.0"
gradle-nexus-publish-plugin = "2.0.0"
spotless = "8.0.0"

[libraries]
# openTCS dependencies
opentcs-api-injection = { group = "org.opentcs", name = "opentcs-api-injection", version.ref = "opentcs-baseline" }
opentcs-common = { group = "org.opentcs", name = "opentcs-common", version.ref = "opentcs-baseline" }
# Other dependencies
eclipse-paho-client-mqttv3 = { group = "org.eclipse.paho", name = "org.eclipse.paho.client.mqttv3", version.ref = "eclipse-paho" }
everit-json-schema = { group = "com.github.erosb", name = "everit-json-schema", version.ref = "everit-json-schema" }
google-code-findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "google-code-findbugs" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
slf4j-jdk14 = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }
# Test dependencies
approvaltests = { group = "com.approvaltests", name = "approvaltests", version.ref = "approvaltests" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = 'hamcrest' }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }

[plugins]
gradle-nexus-publish-plugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradle-nexus-publish-plugin" }
jacocolog = { id = "org.barfuin.gradle.jacocolog", version.ref = "jacocolog" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
